// Code generated by lister-gen. DO NOT EDIT.

package v1

// ConsoleListerExpansion allows custom methods to be added to
// ConsoleLister.
type ConsoleListerExpansion interface{}

// KubeAPIServerListerExpansion allows custom methods to be added to
// KubeAPIServerLister.
type KubeAPIServerListerExpansion interface{}

// KubeControllerManagerListerExpansion allows custom methods to be added to
// KubeControllerManagerLister.
type KubeControllerManagerListerExpansion interface{}

// OpenShiftAPIServerListerExpansion allows custom methods to be added to
// OpenShiftAPIServerLister.
type OpenShiftAPIServerListerExpansion interface{}

// OpenShiftControllerManagerListerExpansion allows custom methods to be added to
// OpenShiftControllerManagerLister.
type OpenShiftControllerManagerListerExpansion interface{}
