// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	consolev1 "github.com/openshift/api/console/v1"
	applyconfigurationsconsolev1 "github.com/openshift/client-go/console/applyconfigurations/console/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConsoleSamples implements ConsoleSampleInterface
type FakeConsoleSamples struct {
	Fake *FakeConsoleV1
}

var consolesamplesResource = schema.GroupVersionResource{Group: "console.openshift.io", Version: "v1", Resource: "consolesamples"}

var consolesamplesKind = schema.GroupVersionKind{Group: "console.openshift.io", Version: "v1", Kind: "ConsoleSample"}

// Get takes name of the consoleSample, and returns the corresponding consoleSample object, and an error if there is any.
func (c *FakeConsoleSamples) Get(ctx context.Context, name string, options v1.GetOptions) (result *consolev1.ConsoleSample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(consolesamplesResource, name), &consolev1.ConsoleSample{})
	if obj == nil {
		return nil, err
	}
	return obj.(*consolev1.ConsoleSample), err
}

// List takes label and field selectors, and returns the list of ConsoleSamples that match those selectors.
func (c *FakeConsoleSamples) List(ctx context.Context, opts v1.ListOptions) (result *consolev1.ConsoleSampleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(consolesamplesResource, consolesamplesKind, opts), &consolev1.ConsoleSampleList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &consolev1.ConsoleSampleList{ListMeta: obj.(*consolev1.ConsoleSampleList).ListMeta}
	for _, item := range obj.(*consolev1.ConsoleSampleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested consoleSamples.
func (c *FakeConsoleSamples) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(consolesamplesResource, opts))
}

// Create takes the representation of a consoleSample and creates it.  Returns the server's representation of the consoleSample, and an error, if there is any.
func (c *FakeConsoleSamples) Create(ctx context.Context, consoleSample *consolev1.ConsoleSample, opts v1.CreateOptions) (result *consolev1.ConsoleSample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(consolesamplesResource, consoleSample), &consolev1.ConsoleSample{})
	if obj == nil {
		return nil, err
	}
	return obj.(*consolev1.ConsoleSample), err
}

// Update takes the representation of a consoleSample and updates it. Returns the server's representation of the consoleSample, and an error, if there is any.
func (c *FakeConsoleSamples) Update(ctx context.Context, consoleSample *consolev1.ConsoleSample, opts v1.UpdateOptions) (result *consolev1.ConsoleSample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(consolesamplesResource, consoleSample), &consolev1.ConsoleSample{})
	if obj == nil {
		return nil, err
	}
	return obj.(*consolev1.ConsoleSample), err
}

// Delete takes name of the consoleSample and deletes it. Returns an error if one occurs.
func (c *FakeConsoleSamples) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(consolesamplesResource, name, opts), &consolev1.ConsoleSample{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConsoleSamples) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(consolesamplesResource, listOpts)

	_, err := c.Fake.Invokes(action, &consolev1.ConsoleSampleList{})
	return err
}

// Patch applies the patch and returns the patched consoleSample.
func (c *FakeConsoleSamples) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *consolev1.ConsoleSample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(consolesamplesResource, name, pt, data, subresources...), &consolev1.ConsoleSample{})
	if obj == nil {
		return nil, err
	}
	return obj.(*consolev1.ConsoleSample), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied consoleSample.
func (c *FakeConsoleSamples) Apply(ctx context.Context, consoleSample *applyconfigurationsconsolev1.ConsoleSampleApplyConfiguration, opts v1.ApplyOptions) (result *consolev1.ConsoleSample, err error) {
	if consoleSample == nil {
		return nil, fmt.Errorf("consoleSample provided to Apply must not be nil")
	}
	data, err := json.Marshal(consoleSample)
	if err != nil {
		return nil, err
	}
	name := consoleSample.Name
	if name == nil {
		return nil, fmt.Errorf("consoleSample.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(consolesamplesResource, *name, types.ApplyPatchType, data), &consolev1.ConsoleSample{})
	if obj == nil {
		return nil, err
	}
	return obj.(*consolev1.ConsoleSample), err
}
