// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/openshift/api/console/v1"
	consolev1 "github.com/openshift/client-go/console/applyconfigurations/console/v1"
	typedconsolev1 "github.com/openshift/client-go/console/clientset/versioned/typed/console/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeConsoleLinks implements ConsoleLinkInterface
type fakeConsoleLinks struct {
	*gentype.FakeClientWithListAndApply[*v1.ConsoleLink, *v1.ConsoleLinkList, *consolev1.ConsoleLinkApplyConfiguration]
	Fake *FakeConsoleV1
}

func newFakeConsoleLinks(fake *FakeConsoleV1) typedconsolev1.ConsoleLinkInterface {
	return &fakeConsoleLinks{
		gentype.NewFakeClientWithListAndApply[*v1.ConsoleLink, *v1.ConsoleLinkList, *consolev1.ConsoleLinkApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("consolelinks"),
			v1.SchemeGroupVersion.WithKind("ConsoleLink"),
			func() *v1.ConsoleLink { return &v1.ConsoleLink{} },
			func() *v1.ConsoleLinkList { return &v1.ConsoleLinkList{} },
			func(dst, src *v1.ConsoleLinkList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ConsoleLinkList) []*v1.ConsoleLink { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ConsoleLinkList, items []*v1.ConsoleLink) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
