// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/openshift/api/console/v1"
	consolev1 "github.com/openshift/client-go/console/applyconfigurations/console/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConsolePlugins implements ConsolePluginInterface
type FakeConsolePlugins struct {
	Fake *FakeConsoleV1
}

var consolepluginsResource = v1.SchemeGroupVersion.WithResource("consoleplugins")

var consolepluginsKind = v1.SchemeGroupVersion.WithKind("ConsolePlugin")

// Get takes name of the consolePlugin, and returns the corresponding consolePlugin object, and an error if there is any.
func (c *FakeConsolePlugins) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ConsolePlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(consolepluginsResource, name), &v1.ConsolePlugin{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConsolePlugin), err
}

// List takes label and field selectors, and returns the list of ConsolePlugins that match those selectors.
func (c *FakeConsolePlugins) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ConsolePluginList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(consolepluginsResource, consolepluginsKind, opts), &v1.ConsolePluginList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ConsolePluginList{ListMeta: obj.(*v1.ConsolePluginList).ListMeta}
	for _, item := range obj.(*v1.ConsolePluginList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested consolePlugins.
func (c *FakeConsolePlugins) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(consolepluginsResource, opts))
}

// Create takes the representation of a consolePlugin and creates it.  Returns the server's representation of the consolePlugin, and an error, if there is any.
func (c *FakeConsolePlugins) Create(ctx context.Context, consolePlugin *v1.ConsolePlugin, opts metav1.CreateOptions) (result *v1.ConsolePlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(consolepluginsResource, consolePlugin), &v1.ConsolePlugin{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConsolePlugin), err
}

// Update takes the representation of a consolePlugin and updates it. Returns the server's representation of the consolePlugin, and an error, if there is any.
func (c *FakeConsolePlugins) Update(ctx context.Context, consolePlugin *v1.ConsolePlugin, opts metav1.UpdateOptions) (result *v1.ConsolePlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(consolepluginsResource, consolePlugin), &v1.ConsolePlugin{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConsolePlugin), err
}

// Delete takes name of the consolePlugin and deletes it. Returns an error if one occurs.
func (c *FakeConsolePlugins) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(consolepluginsResource, name, opts), &v1.ConsolePlugin{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConsolePlugins) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(consolepluginsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ConsolePluginList{})
	return err
}

// Patch applies the patch and returns the patched consolePlugin.
func (c *FakeConsolePlugins) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ConsolePlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(consolepluginsResource, name, pt, data, subresources...), &v1.ConsolePlugin{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConsolePlugin), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied consolePlugin.
func (c *FakeConsolePlugins) Apply(ctx context.Context, consolePlugin *consolev1.ConsolePluginApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ConsolePlugin, err error) {
	if consolePlugin == nil {
		return nil, fmt.Errorf("consolePlugin provided to Apply must not be nil")
	}
	data, err := json.Marshal(consolePlugin)
	if err != nil {
		return nil, err
	}
	name := consolePlugin.Name
	if name == nil {
		return nil, fmt.Errorf("consolePlugin.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(consolepluginsResource, *name, types.ApplyPatchType, data), &v1.ConsolePlugin{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConsolePlugin), err
}
