// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "github.com/openshift/api/config/v1"
)

// ConnectionConfigNamespaceScopedApplyConfiguration represents a declarative configuration of the ConnectionConfigNamespaceScoped type for use
// with apply.
type ConnectionConfigNamespaceScopedApplyConfiguration struct {
	URL             *string                    `json:"url,omitempty"`
	CA              *v1.ConfigMapNameReference `json:"ca,omitempty"`
	TLSClientConfig *v1.SecretNameReference    `json:"tlsClientConfig,omitempty"`
	BasicAuthConfig *v1.SecretNameReference    `json:"basicAuthConfig,omitempty"`
}

// ConnectionConfigNamespaceScopedApplyConfiguration constructs a declarative configuration of the ConnectionConfigNamespaceScoped type for use with
// apply.
func ConnectionConfigNamespaceScoped() *ConnectionConfigNamespaceScopedApplyConfiguration {
	return &ConnectionConfigNamespaceScopedApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *ConnectionConfigNamespaceScopedApplyConfiguration) WithURL(value string) *ConnectionConfigNamespaceScopedApplyConfiguration {
	b.URL = &value
	return b
}

// WithCA sets the CA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CA field is set to the value of the last call.
func (b *ConnectionConfigNamespaceScopedApplyConfiguration) WithCA(value v1.ConfigMapNameReference) *ConnectionConfigNamespaceScopedApplyConfiguration {
	b.CA = &value
	return b
}

// WithTLSClientConfig sets the TLSClientConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSClientConfig field is set to the value of the last call.
func (b *ConnectionConfigNamespaceScopedApplyConfiguration) WithTLSClientConfig(value v1.SecretNameReference) *ConnectionConfigNamespaceScopedApplyConfiguration {
	b.TLSClientConfig = &value
	return b
}

// WithBasicAuthConfig sets the BasicAuthConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BasicAuthConfig field is set to the value of the last call.
func (b *ConnectionConfigNamespaceScopedApplyConfiguration) WithBasicAuthConfig(value v1.SecretNameReference) *ConnectionConfigNamespaceScopedApplyConfiguration {
	b.BasicAuthConfig = &value
	return b
}
