// Code generated by lister-gen. DO NOT EDIT.

package v1

// CriticalResourceListerExpansion allows custom methods to be added to
// CriticalResourceLister.
type CriticalResourceListerExpansion interface{}

// CriticalResourceNamespaceListerExpansion allows custom methods to be added to
// CriticalResourceNamespaceLister.
type CriticalResourceNamespaceListerExpansion interface{}
