// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/openshift/api/quota/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	testing "k8s.io/client-go/testing"
)

// FakeAppliedClusterResourceQuotas implements AppliedClusterResourceQuotaInterface
type FakeAppliedClusterResourceQuotas struct {
	Fake *FakeQuotaV1
	ns   string
}

var appliedclusterresourcequotasResource = v1.SchemeGroupVersion.WithResource("appliedclusterresourcequotas")

var appliedclusterresourcequotasKind = v1.SchemeGroupVersion.WithKind("AppliedClusterResourceQuota")

// Get takes name of the appliedClusterResourceQuota, and returns the corresponding appliedClusterResourceQuota object, and an error if there is any.
func (c *FakeAppliedClusterResourceQuotas) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AppliedClusterResourceQuota, err error) {
	emptyResult := &v1.AppliedClusterResourceQuota{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(appliedclusterresourcequotasResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.AppliedClusterResourceQuota), err
}

// List takes label and field selectors, and returns the list of AppliedClusterResourceQuotas that match those selectors.
func (c *FakeAppliedClusterResourceQuotas) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AppliedClusterResourceQuotaList, err error) {
	emptyResult := &v1.AppliedClusterResourceQuotaList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(appliedclusterresourcequotasResource, appliedclusterresourcequotasKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.AppliedClusterResourceQuotaList{ListMeta: obj.(*v1.AppliedClusterResourceQuotaList).ListMeta}
	for _, item := range obj.(*v1.AppliedClusterResourceQuotaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}
