// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	machinev1 "github.com/openshift/api/machine/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAWSPlacementGroups implements AWSPlacementGroupInterface
type FakeAWSPlacementGroups struct {
	Fake *FakeMachineV1
	ns   string
}

var awsplacementgroupsResource = schema.GroupVersionResource{Group: "machine.openshift.io", Version: "v1", Resource: "awsplacementgroups"}

var awsplacementgroupsKind = schema.GroupVersionKind{Group: "machine.openshift.io", Version: "v1", Kind: "AWSPlacementGroup"}

// Get takes name of the aWSPlacementGroup, and returns the corresponding aWSPlacementGroup object, and an error if there is any.
func (c *FakeAWSPlacementGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *machinev1.AWSPlacementGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsplacementgroupsResource, c.ns, name), &machinev1.AWSPlacementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machinev1.AWSPlacementGroup), err
}

// List takes label and field selectors, and returns the list of AWSPlacementGroups that match those selectors.
func (c *FakeAWSPlacementGroups) List(ctx context.Context, opts v1.ListOptions) (result *machinev1.AWSPlacementGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsplacementgroupsResource, awsplacementgroupsKind, c.ns, opts), &machinev1.AWSPlacementGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &machinev1.AWSPlacementGroupList{ListMeta: obj.(*machinev1.AWSPlacementGroupList).ListMeta}
	for _, item := range obj.(*machinev1.AWSPlacementGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aWSPlacementGroups.
func (c *FakeAWSPlacementGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsplacementgroupsResource, c.ns, opts))

}

// Create takes the representation of a aWSPlacementGroup and creates it.  Returns the server's representation of the aWSPlacementGroup, and an error, if there is any.
func (c *FakeAWSPlacementGroups) Create(ctx context.Context, aWSPlacementGroup *machinev1.AWSPlacementGroup, opts v1.CreateOptions) (result *machinev1.AWSPlacementGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsplacementgroupsResource, c.ns, aWSPlacementGroup), &machinev1.AWSPlacementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machinev1.AWSPlacementGroup), err
}

// Update takes the representation of a aWSPlacementGroup and updates it. Returns the server's representation of the aWSPlacementGroup, and an error, if there is any.
func (c *FakeAWSPlacementGroups) Update(ctx context.Context, aWSPlacementGroup *machinev1.AWSPlacementGroup, opts v1.UpdateOptions) (result *machinev1.AWSPlacementGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsplacementgroupsResource, c.ns, aWSPlacementGroup), &machinev1.AWSPlacementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machinev1.AWSPlacementGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAWSPlacementGroups) UpdateStatus(ctx context.Context, aWSPlacementGroup *machinev1.AWSPlacementGroup, opts v1.UpdateOptions) (*machinev1.AWSPlacementGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(awsplacementgroupsResource, "status", c.ns, aWSPlacementGroup), &machinev1.AWSPlacementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machinev1.AWSPlacementGroup), err
}

// Delete takes name of the aWSPlacementGroup and deletes it. Returns an error if one occurs.
func (c *FakeAWSPlacementGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(awsplacementgroupsResource, c.ns, name, opts), &machinev1.AWSPlacementGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAWSPlacementGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsplacementgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &machinev1.AWSPlacementGroupList{})
	return err
}

// Patch applies the patch and returns the patched aWSPlacementGroup.
func (c *FakeAWSPlacementGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *machinev1.AWSPlacementGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsplacementgroupsResource, c.ns, name, pt, data, subresources...), &machinev1.AWSPlacementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machinev1.AWSPlacementGroup), err
}
