// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DataGatherStatusApplyConfiguration represents a declarative configuration of the DataGatherStatus type for use
// with apply.
//
// DataGatherStatus contains information relating to the DataGather state.
type DataGatherStatusApplyConfiguration struct {
	// conditions is an optional field that provides details on the status of the gatherer job.
	// It may not exceed 100 items and must not contain duplicates.
	//
	// # The current condition types are DataUploaded, DataRecorded, DataProcessed, RemoteConfigurationNotAvailable, RemoteConfigurationInvalid
	//
	// The DataUploaded condition is used to represent whether or not the archive was successfully uploaded for further processing.
	// When it has a status of True and a reason of Succeeded, the archive was successfully uploaded.
	// When it has a status of Unknown and a reason of NoUploadYet, the upload has not occurred, or there was no data to upload.
	// When it has a status of False and a reason Failed, the upload failed. The accompanying message will include the specific error encountered.
	//
	// The DataRecorded condition is used to represent whether or not the archive was successfully recorded.
	// When it has a status of True and a reason of Succeeded, the archive was recorded successfully.
	// When it has a status of Unknown and a reason of NoDataGatheringYet, the data gathering process has not started yet.
	// When it has a status of False and a reason of RecordingFailed, the recording failed and a message will include the specific error encountered.
	//
	// The DataProcessed condition is used to represent whether or not the archive was processed by the processing service.
	// When it has a status of True and a reason of Processed, the data was processed successfully.
	// When it has a status of Unknown and a reason of NothingToProcessYet, there is no data to process at the moment.
	// When it has a status of False and a reason of Failure, processing failed and a message will include the specific error encountered.
	//
	// The RemoteConfigurationAvailable condition is used to represent whether the remote configuration is available.
	// When it has a status of Unknown and a reason of Unknown or RemoteConfigNotRequestedYet, the state of the remote configuration is unknown—typically at startup.
	// When it has a status of True and a reason of Succeeded, the configuration is available.
	// When it has a status of False and a reason of NoToken, the configuration was disabled by removing the cloud.openshift.com field from the pull secret.
	// When it has a status of False and a reason of DisabledByConfiguration, the configuration was disabled in insightsdatagather.config.openshift.io.
	//
	// The RemoteConfigurationValid condition is used to represent whether the remote configuration is valid.
	// When it has a status of Unknown and a reason of Unknown or NoValidationYet, the validity of the remote configuration is unknown—typically at startup.
	// When it has a status of True and a reason of Succeeded, the configuration is valid.
	// When it has a status of False and a reason of Invalid, the configuration is invalid.
	//
	// The Progressing condition is used to represent the phase of gathering
	// When it has a status of False and the reason is DataGatherPending, the gathering has not started yet.
	// When it has a status of True and reason is Gathering, the gathering is running.
	// When it has a status of False and reason is GatheringSucceeded, the gathering succesfully finished.
	// When it has a status of False and reason is GatheringFailed, the gathering failed.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// gatherers is a list of active gatherers (and their statuses) in the last gathering.
	Gatherers []GathererStatusApplyConfiguration `json:"gatherers,omitempty"`
	// startTime is the time when Insights data gathering started.
	StartTime *metav1.Time `json:"startTime,omitempty"`
	// finishTime is the time when Insights data gathering finished.
	FinishTime *metav1.Time `json:"finishTime,omitempty"`
	// relatedObjects is an optional list of resources which are useful when debugging or inspecting the data gathering Pod
	// It may not exceed 100 items and must not contain duplicates.
	RelatedObjects []ObjectReferenceApplyConfiguration `json:"relatedObjects,omitempty"`
	// insightsRequestID is an optional Insights request ID to track the status of the Insights analysis (in console.redhat.com processing pipeline) for the corresponding Insights data archive.
	// It may not exceed 256 characters and is immutable once set.
	InsightsRequestID *string `json:"insightsRequestID,omitempty"`
	// insightsReport provides general Insights analysis results.
	// When omitted, this means no data gathering has taken place yet or the
	// corresponding Insights analysis (identified by "insightsRequestID") is not available.
	InsightsReport *InsightsReportApplyConfiguration `json:"insightsReport,omitempty"`
}

// DataGatherStatusApplyConfiguration constructs a declarative configuration of the DataGatherStatus type for use with
// apply.
func DataGatherStatus() *DataGatherStatusApplyConfiguration {
	return &DataGatherStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DataGatherStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *DataGatherStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithGatherers adds the given value to the Gatherers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Gatherers field.
func (b *DataGatherStatusApplyConfiguration) WithGatherers(values ...*GathererStatusApplyConfiguration) *DataGatherStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithGatherers")
		}
		b.Gatherers = append(b.Gatherers, *values[i])
	}
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *DataGatherStatusApplyConfiguration) WithStartTime(value metav1.Time) *DataGatherStatusApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithFinishTime sets the FinishTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FinishTime field is set to the value of the last call.
func (b *DataGatherStatusApplyConfiguration) WithFinishTime(value metav1.Time) *DataGatherStatusApplyConfiguration {
	b.FinishTime = &value
	return b
}

// WithRelatedObjects adds the given value to the RelatedObjects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RelatedObjects field.
func (b *DataGatherStatusApplyConfiguration) WithRelatedObjects(values ...*ObjectReferenceApplyConfiguration) *DataGatherStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRelatedObjects")
		}
		b.RelatedObjects = append(b.RelatedObjects, *values[i])
	}
	return b
}

// WithInsightsRequestID sets the InsightsRequestID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsightsRequestID field is set to the value of the last call.
func (b *DataGatherStatusApplyConfiguration) WithInsightsRequestID(value string) *DataGatherStatusApplyConfiguration {
	b.InsightsRequestID = &value
	return b
}

// WithInsightsReport sets the InsightsReport field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsightsReport field is set to the value of the last call.
func (b *DataGatherStatusApplyConfiguration) WithInsightsReport(value *InsightsReportApplyConfiguration) *DataGatherStatusApplyConfiguration {
	b.InsightsReport = value
	return b
}
