// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/client-go/apiextensions/clientset/versioned/typed/apiextensions/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeApiextensionsV1alpha1 struct {
	*testing.Fake
}

func (c *FakeApiextensionsV1alpha1) CompatibilityRequirements() v1alpha1.CompatibilityRequirementInterface {
	return newFakeCompatibilityRequirements(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeApiextensionsV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
