// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apimachineconfigurationv1 "github.com/openshift/api/machineconfiguration/v1"
	versioned "github.com/openshift/client-go/machineconfiguration/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/machineconfiguration/informers/externalversions/internalinterfaces"
	machineconfigurationv1 "github.com/openshift/client-go/machineconfiguration/listers/machineconfiguration/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InternalReleaseImageInformer provides access to a shared informer and lister for
// InternalReleaseImages. Prefer using the type-safe variant (see [TypedInternalReleaseImageInformer]).
type InternalReleaseImageInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() machineconfigurationv1.InternalReleaseImageLister
}

// TypedInternalReleaseImageInformer provides access to a shared informer and lister for
// InternalReleaseImages, including the type-safe TypedInformer variant.
// It is a superset of InternalReleaseImageInformer.
type TypedInternalReleaseImageInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() InternalReleaseImageIndexInformer
	Lister() machineconfigurationv1.InternalReleaseImageLister
}

// InternalReleaseImageIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type InternalReleaseImageIndexInformer cache.TypedSharedIndexInformer[*apimachineconfigurationv1.InternalReleaseImage]

// InternalReleaseImageHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for InternalReleaseImage.
type InternalReleaseImageHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apimachineconfigurationv1.InternalReleaseImage]

// InternalReleaseImageDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for InternalReleaseImage.
type InternalReleaseImageDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apimachineconfigurationv1.InternalReleaseImage]

// InternalReleaseImageFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for InternalReleaseImage.
type InternalReleaseImageFilteringHandler = cache.TypedFilteringResourceEventHandler[*apimachineconfigurationv1.InternalReleaseImage]

// InternalReleaseImageIndexers is a specialization of [cache.TypedIndexers] for InternalReleaseImage.
type InternalReleaseImageIndexers = cache.TypedIndexers[*apimachineconfigurationv1.InternalReleaseImage]

// DeletedInternalReleaseImage is a specialization of [cache.DeletedObject] for InternalReleaseImage.
type DeletedInternalReleaseImage = cache.DeletedObject[*apimachineconfigurationv1.InternalReleaseImage]

type internalReleaseImageInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewInternalReleaseImageInformer constructs a new informer for InternalReleaseImage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedInternalReleaseImageInformer]).
func NewInternalReleaseImageInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewInternalReleaseImageInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedInternalReleaseImageInformer constructs a new informer for InternalReleaseImage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedInternalReleaseImageInformer(client versioned.Interface, resyncPeriod time.Duration, indexers InternalReleaseImageIndexers) InternalReleaseImageIndexInformer {
	return NewTypedInternalReleaseImageInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredInternalReleaseImageInformer constructs a new informer for InternalReleaseImage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredInternalReleaseImageInformer]).
func NewFilteredInternalReleaseImageInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedInternalReleaseImageInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredInternalReleaseImageInformer constructs a new informer for InternalReleaseImage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredInternalReleaseImageInformer(client versioned.Interface, resyncPeriod time.Duration, indexers InternalReleaseImageIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) InternalReleaseImageIndexInformer {
	return NewTypedInternalReleaseImageInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewInternalReleaseImageInformerWithOptions constructs a new informer for InternalReleaseImage type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedInternalReleaseImageInformerWithOptions]).
func NewInternalReleaseImageInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedInternalReleaseImageInformerWithOptions(client, options)
}

// NewTypedInternalReleaseImageInformerWithOptions constructs a new informer for InternalReleaseImage type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedInternalReleaseImageInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) InternalReleaseImageIndexInformer {
	gvr := schema.GroupVersionResource{Group: "machineconfiguration.openshift.io", Version: "v1", Resource: "internalreleaseimages"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apimachineconfigurationv1.InternalReleaseImage](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MachineconfigurationV1().InternalReleaseImages().List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MachineconfigurationV1().InternalReleaseImages().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MachineconfigurationV1().InternalReleaseImages().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MachineconfigurationV1().InternalReleaseImages().Watch(ctx, opts)
			},
		}, client),
		&apimachineconfigurationv1.InternalReleaseImage{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *internalReleaseImageInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedInternalReleaseImageInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *internalReleaseImageInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *internalReleaseImageInformer) TypedInformer() InternalReleaseImageIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apimachineconfigurationv1.InternalReleaseImage](f.factory.InformerFor(&apimachineconfigurationv1.InternalReleaseImage{}, f.defaultInformer))
}

func (f *internalReleaseImageInformer) Lister() machineconfigurationv1.InternalReleaseImageLister {
	return machineconfigurationv1.NewInternalReleaseImageLister(f.Informer().GetIndexer())
}

// ToTypedInternalReleaseImageInformer converts an untyped informer into a TypedInternalReleaseImageInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *InternalReleaseImage. If that is not the case, calling type-safe methods of the returned
// TypedInternalReleaseImageInformer leads to runtime panics. A safer alternative is to pass
// around a TypedInternalReleaseImageInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedInternalReleaseImageInformer(informer InternalReleaseImageInformer) TypedInternalReleaseImageInformer {
	if informer, ok := informer.(TypedInternalReleaseImageInformer); ok {
		return informer
	}
	return &internalReleaseImageTypedInformerAdapter{informer}
}

type internalReleaseImageTypedInformerAdapter struct {
	InternalReleaseImageInformer
}

func (a *internalReleaseImageTypedInformerAdapter) TypedInformer() InternalReleaseImageIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apimachineconfigurationv1.InternalReleaseImage](a.Informer())
}

// ToInternalReleaseImageIndexInformer converts an untyped informer into a InternalReleaseImageIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *InternalReleaseImage. If that is not the case, calling type-safe methods of the returned
// InternalReleaseImageIndexInformer leads to runtime panics. A safer alternative is to pass
// around a InternalReleaseImageIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToInternalReleaseImageIndexInformer(informer cache.SharedIndexInformer) InternalReleaseImageIndexInformer {
	if informer, ok := informer.(InternalReleaseImageIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apimachineconfigurationv1.InternalReleaseImage](informer)
}
