// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/openshift/client-go/machineconfiguration/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ContainerRuntimeConfigs returns a ContainerRuntimeConfigInformer.
	ContainerRuntimeConfigs() TypedContainerRuntimeConfigInformer
	// ControllerConfigs returns a ControllerConfigInformer.
	ControllerConfigs() TypedControllerConfigInformer
	// InternalReleaseImages returns a InternalReleaseImageInformer.
	InternalReleaseImages() TypedInternalReleaseImageInformer
	// KubeletConfigs returns a KubeletConfigInformer.
	KubeletConfigs() TypedKubeletConfigInformer
	// MachineConfigs returns a MachineConfigInformer.
	MachineConfigs() TypedMachineConfigInformer
	// MachineConfigNodes returns a MachineConfigNodeInformer.
	MachineConfigNodes() TypedMachineConfigNodeInformer
	// MachineConfigPools returns a MachineConfigPoolInformer.
	MachineConfigPools() TypedMachineConfigPoolInformer
	// MachineOSBuilds returns a MachineOSBuildInformer.
	MachineOSBuilds() TypedMachineOSBuildInformer
	// MachineOSConfigs returns a MachineOSConfigInformer.
	MachineOSConfigs() TypedMachineOSConfigInformer
	// OSImageStreams returns a OSImageStreamInformer.
	OSImageStreams() TypedOSImageStreamInformer
	// PinnedImageSets returns a PinnedImageSetInformer.
	PinnedImageSets() TypedPinnedImageSetInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ContainerRuntimeConfigs returns a TypedContainerRuntimeConfigInformer.
func (v *version) ContainerRuntimeConfigs() TypedContainerRuntimeConfigInformer {
	return &containerRuntimeConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ControllerConfigs returns a TypedControllerConfigInformer.
func (v *version) ControllerConfigs() TypedControllerConfigInformer {
	return &controllerConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// InternalReleaseImages returns a TypedInternalReleaseImageInformer.
func (v *version) InternalReleaseImages() TypedInternalReleaseImageInformer {
	return &internalReleaseImageInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// KubeletConfigs returns a TypedKubeletConfigInformer.
func (v *version) KubeletConfigs() TypedKubeletConfigInformer {
	return &kubeletConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// MachineConfigs returns a TypedMachineConfigInformer.
func (v *version) MachineConfigs() TypedMachineConfigInformer {
	return &machineConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// MachineConfigNodes returns a TypedMachineConfigNodeInformer.
func (v *version) MachineConfigNodes() TypedMachineConfigNodeInformer {
	return &machineConfigNodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// MachineConfigPools returns a TypedMachineConfigPoolInformer.
func (v *version) MachineConfigPools() TypedMachineConfigPoolInformer {
	return &machineConfigPoolInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// MachineOSBuilds returns a TypedMachineOSBuildInformer.
func (v *version) MachineOSBuilds() TypedMachineOSBuildInformer {
	return &machineOSBuildInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// MachineOSConfigs returns a TypedMachineOSConfigInformer.
func (v *version) MachineOSConfigs() TypedMachineOSConfigInformer {
	return &machineOSConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// OSImageStreams returns a TypedOSImageStreamInformer.
func (v *version) OSImageStreams() TypedOSImageStreamInformer {
	return &oSImageStreamInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// PinnedImageSets returns a TypedPinnedImageSetInformer.
func (v *version) PinnedImageSets() TypedPinnedImageSetInformer {
	return &pinnedImageSetInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
