// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/openshift/api/monitoring/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// AlertRelabelConfigLister helps list AlertRelabelConfigs.
// All objects returned here must be treated as read-only.
type AlertRelabelConfigLister interface {
	// List lists all AlertRelabelConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.AlertRelabelConfig, err error)
	// AlertRelabelConfigs returns an object that can list and get AlertRelabelConfigs.
	AlertRelabelConfigs(namespace string) AlertRelabelConfigNamespaceLister
	AlertRelabelConfigListerExpansion
}

// alertRelabelConfigLister implements the AlertRelabelConfigLister interface.
type alertRelabelConfigLister struct {
	listers.ResourceIndexer[*v1.AlertRelabelConfig]
}

// NewAlertRelabelConfigLister returns a new AlertRelabelConfigLister.
func NewAlertRelabelConfigLister(indexer cache.Indexer) AlertRelabelConfigLister {
	return &alertRelabelConfigLister{listers.New[*v1.AlertRelabelConfig](indexer, v1.Resource("alertrelabelconfig"))}
}

// AlertRelabelConfigs returns an object that can list and get AlertRelabelConfigs.
func (s *alertRelabelConfigLister) AlertRelabelConfigs(namespace string) AlertRelabelConfigNamespaceLister {
	return alertRelabelConfigNamespaceLister{listers.NewNamespaced[*v1.AlertRelabelConfig](s.ResourceIndexer, namespace)}
}

// AlertRelabelConfigNamespaceLister helps list and get AlertRelabelConfigs.
// All objects returned here must be treated as read-only.
type AlertRelabelConfigNamespaceLister interface {
	// List lists all AlertRelabelConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.AlertRelabelConfig, err error)
	// Get retrieves the AlertRelabelConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.AlertRelabelConfig, error)
	AlertRelabelConfigNamespaceListerExpansion
}

// alertRelabelConfigNamespaceLister implements the AlertRelabelConfigNamespaceLister
// interface.
type alertRelabelConfigNamespaceLister struct {
	listers.ResourceIndexer[*v1.AlertRelabelConfig]
}
