// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/openshift/api/samples/v1"
	samplesv1 "github.com/openshift/client-go/samples/applyconfigurations/samples/v1"
	typedsamplesv1 "github.com/openshift/client-go/samples/clientset/versioned/typed/samples/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeConfigs implements ConfigInterface
type fakeConfigs struct {
	*gentype.FakeClientWithListAndApply[*v1.Config, *v1.ConfigList, *samplesv1.ConfigApplyConfiguration]
	Fake *FakeSamplesV1
}

func newFakeConfigs(fake *FakeSamplesV1) typedsamplesv1.ConfigInterface {
	return &fakeConfigs{
		gentype.NewFakeClientWithListAndApply[*v1.Config, *v1.ConfigList, *samplesv1.ConfigApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("configs"),
			v1.SchemeGroupVersion.WithKind("Config"),
			func() *v1.Config { return &v1.Config{} },
			func() *v1.ConfigList { return &v1.ConfigList{} },
			func(dst, src *v1.ConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ConfigList) []*v1.Config { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ConfigList, items []*v1.Config) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
