// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1 "github.com/openshift/api/cloudnetwork/v1"
	cloudnetworkv1 "github.com/openshift/client-go/cloudnetwork/applyconfigurations/cloudnetwork/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=cloud.network.openshift.io, Version=v1
	case v1.SchemeGroupVersion.WithKind("CloudPrivateIPConfig"):
		return &cloudnetworkv1.CloudPrivateIPConfigApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CloudPrivateIPConfigSpec"):
		return &cloudnetworkv1.CloudPrivateIPConfigSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CloudPrivateIPConfigStatus"):
		return &cloudnetworkv1.CloudPrivateIPConfigStatusApplyConfiguration{}

	}
	return nil
}
