// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	consolev1 "github.com/openshift/api/console/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ConsoleCLIDownloadLister helps list ConsoleCLIDownloads.
// All objects returned here must be treated as read-only.
type ConsoleCLIDownloadLister interface {
	// List lists all ConsoleCLIDownloads in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*consolev1.ConsoleCLIDownload, err error)
	// Get retrieves the ConsoleCLIDownload from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*consolev1.ConsoleCLIDownload, error)
	ConsoleCLIDownloadListerExpansion
}

// consoleCLIDownloadLister implements the ConsoleCLIDownloadLister interface.
type consoleCLIDownloadLister struct {
	listers.ResourceIndexer[*consolev1.ConsoleCLIDownload]
}

// NewConsoleCLIDownloadLister returns a new ConsoleCLIDownloadLister.
func NewConsoleCLIDownloadLister(indexer cache.Indexer) ConsoleCLIDownloadLister {
	return &consoleCLIDownloadLister{listers.New[*consolev1.ConsoleCLIDownload](indexer, consolev1.Resource("consoleclidownload"))}
}
