// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	consolev1 "github.com/openshift/api/console/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ConsoleQuickStartLister helps list ConsoleQuickStarts.
// All objects returned here must be treated as read-only.
type ConsoleQuickStartLister interface {
	// List lists all ConsoleQuickStarts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*consolev1.ConsoleQuickStart, err error)
	// Get retrieves the ConsoleQuickStart from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*consolev1.ConsoleQuickStart, error)
	ConsoleQuickStartListerExpansion
}

// consoleQuickStartLister implements the ConsoleQuickStartLister interface.
type consoleQuickStartLister struct {
	listers.ResourceIndexer[*consolev1.ConsoleQuickStart]
}

// NewConsoleQuickStartLister returns a new ConsoleQuickStartLister.
func NewConsoleQuickStartLister(indexer cache.Indexer) ConsoleQuickStartLister {
	return &consoleQuickStartLister{listers.New[*consolev1.ConsoleQuickStart](indexer, consolev1.Resource("consolequickstart"))}
}
