// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/openshift/api/console/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// ConsoleExternalLogLinkLister helps list ConsoleExternalLogLinks.
// All objects returned here must be treated as read-only.
type ConsoleExternalLogLinkLister interface {
	// List lists all ConsoleExternalLogLinks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ConsoleExternalLogLink, err error)
	// Get retrieves the ConsoleExternalLogLink from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ConsoleExternalLogLink, error)
	ConsoleExternalLogLinkListerExpansion
}

// consoleExternalLogLinkLister implements the ConsoleExternalLogLinkLister interface.
type consoleExternalLogLinkLister struct {
	listers.ResourceIndexer[*v1.ConsoleExternalLogLink]
}

// NewConsoleExternalLogLinkLister returns a new ConsoleExternalLogLinkLister.
func NewConsoleExternalLogLinkLister(indexer cache.Indexer) ConsoleExternalLogLinkLister {
	return &consoleExternalLogLinkLister{listers.New[*v1.ConsoleExternalLogLink](indexer, v1.Resource("consoleexternalloglink"))}
}
