// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	consolev1 "github.com/openshift/api/console/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ConsoleLinkLister helps list ConsoleLinks.
// All objects returned here must be treated as read-only.
type ConsoleLinkLister interface {
	// List lists all ConsoleLinks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*consolev1.ConsoleLink, err error)
	// Get retrieves the ConsoleLink from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*consolev1.ConsoleLink, error)
	ConsoleLinkListerExpansion
}

// consoleLinkLister implements the ConsoleLinkLister interface.
type consoleLinkLister struct {
	listers.ResourceIndexer[*consolev1.ConsoleLink]
}

// NewConsoleLinkLister returns a new ConsoleLinkLister.
func NewConsoleLinkLister(indexer cache.Indexer) ConsoleLinkLister {
	return &consoleLinkLister{listers.New[*consolev1.ConsoleLink](indexer, consolev1.Resource("consolelink"))}
}
