// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	configv1 "github.com/openshift/api/config/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDeschedulers implements DeschedulerInterface
type FakeDeschedulers struct {
	Fake *FakeConfigV1
}

var deschedulersResource = schema.GroupVersionResource{Group: "config.openshift.io", Version: "v1", Resource: "deschedulers"}

var deschedulersKind = schema.GroupVersionKind{Group: "config.openshift.io", Version: "v1", Kind: "Descheduler"}

// Get takes name of the descheduler, and returns the corresponding descheduler object, and an error if there is any.
func (c *FakeDeschedulers) Get(ctx context.Context, name string, options v1.GetOptions) (result *configv1.Descheduler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(deschedulersResource, name), &configv1.Descheduler{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Descheduler), err
}

// List takes label and field selectors, and returns the list of Deschedulers that match those selectors.
func (c *FakeDeschedulers) List(ctx context.Context, opts v1.ListOptions) (result *configv1.DeschedulerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(deschedulersResource, deschedulersKind, opts), &configv1.DeschedulerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &configv1.DeschedulerList{ListMeta: obj.(*configv1.DeschedulerList).ListMeta}
	for _, item := range obj.(*configv1.DeschedulerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested deschedulers.
func (c *FakeDeschedulers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(deschedulersResource, opts))
}

// Create takes the representation of a descheduler and creates it.  Returns the server's representation of the descheduler, and an error, if there is any.
func (c *FakeDeschedulers) Create(ctx context.Context, descheduler *configv1.Descheduler, opts v1.CreateOptions) (result *configv1.Descheduler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(deschedulersResource, descheduler), &configv1.Descheduler{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Descheduler), err
}

// Update takes the representation of a descheduler and updates it. Returns the server's representation of the descheduler, and an error, if there is any.
func (c *FakeDeschedulers) Update(ctx context.Context, descheduler *configv1.Descheduler, opts v1.UpdateOptions) (result *configv1.Descheduler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(deschedulersResource, descheduler), &configv1.Descheduler{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Descheduler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDeschedulers) UpdateStatus(ctx context.Context, descheduler *configv1.Descheduler, opts v1.UpdateOptions) (*configv1.Descheduler, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(deschedulersResource, "status", descheduler), &configv1.Descheduler{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Descheduler), err
}

// Delete takes name of the descheduler and deletes it. Returns an error if one occurs.
func (c *FakeDeschedulers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(deschedulersResource, name), &configv1.Descheduler{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDeschedulers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(deschedulersResource, listOpts)

	_, err := c.Fake.Invokes(action, &configv1.DeschedulerList{})
	return err
}

// Patch applies the patch and returns the patched descheduler.
func (c *FakeDeschedulers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *configv1.Descheduler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(deschedulersResource, name, pt, data, subresources...), &configv1.Descheduler{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Descheduler), err
}
