// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1alpha1 "github.com/openshift/api/apiextensions/v1alpha1"
)

// APIExcludedFieldApplyConfiguration represents a declarative configuration of the APIExcludedField type for use
// with apply.
type APIExcludedFieldApplyConfiguration struct {
	Path     *string                                  `json:"path,omitempty"`
	Versions []apiextensionsv1alpha1.APIVersionString `json:"versions,omitempty"`
}

// APIExcludedFieldApplyConfiguration constructs a declarative configuration of the APIExcludedField type for use with
// apply.
func APIExcludedField() *APIExcludedFieldApplyConfiguration {
	return &APIExcludedFieldApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *APIExcludedFieldApplyConfiguration) WithPath(value string) *APIExcludedFieldApplyConfiguration {
	b.Path = &value
	return b
}

// WithVersions adds the given value to the Versions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Versions field.
func (b *APIExcludedFieldApplyConfiguration) WithVersions(values ...apiextensionsv1alpha1.APIVersionString) *APIExcludedFieldApplyConfiguration {
	for i := range values {
		b.Versions = append(b.Versions, values[i])
	}
	return b
}
