// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1alpha1 "github.com/openshift/api/apiextensions/v1alpha1"
)

// APIVersionsApplyConfiguration represents a declarative configuration of the APIVersions type for use
// with apply.
//
// APIVersions specifies a set of API versions of a CRD.
type APIVersionsApplyConfiguration struct {
	// defaultSelection specifies a method for automatically selecting a set of
	// versions to require.
	//
	// Valid options are StorageOnly and AllServed.
	// When set to StorageOnly, only the storage version is selected for
	// compatibility assessment.
	// When set to AllServed, all served versions are selected for compatibility
	// assessment.
	//
	// This field is required.
	DefaultSelection *apiextensionsv1alpha1.APIVersionSelectionType `json:"defaultSelection,omitempty"`
	// additionalVersions specifies a set api versions to require in addition to
	// the default selection. It is explicitly permitted to specify a version in
	// additionalVersions which was also selected by the default selection. The
	// selections will be merged and deduplicated.
	//
	// Each item must be at most 63 characters in length, and must must consist
	// of only lowercase alphanumeric characters and hyphens, and must start
	// with an alphabetic character and end with an alphanumeric character.// with an alphabetic character and end with an alphanumeric character.
	// At most 32 additional versions may be specified.
	AdditionalVersions []apiextensionsv1alpha1.APIVersionString `json:"additionalVersions,omitempty"`
}

// APIVersionsApplyConfiguration constructs a declarative configuration of the APIVersions type for use with
// apply.
func APIVersions() *APIVersionsApplyConfiguration {
	return &APIVersionsApplyConfiguration{}
}

// WithDefaultSelection sets the DefaultSelection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultSelection field is set to the value of the last call.
func (b *APIVersionsApplyConfiguration) WithDefaultSelection(value apiextensionsv1alpha1.APIVersionSelectionType) *APIVersionsApplyConfiguration {
	b.DefaultSelection = &value
	return b
}

// WithAdditionalVersions adds the given value to the AdditionalVersions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalVersions field.
func (b *APIVersionsApplyConfiguration) WithAdditionalVersions(values ...apiextensionsv1alpha1.APIVersionString) *APIVersionsApplyConfiguration {
	for i := range values {
		b.AdditionalVersions = append(b.AdditionalVersions, values[i])
	}
	return b
}
