// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CompatibilitySchemaApplyConfiguration represents a declarative configuration of the CompatibilitySchema type for use
// with apply.
type CompatibilitySchemaApplyConfiguration struct {
	CustomResourceDefinition *CRDDataApplyConfiguration           `json:"customResourceDefinition,omitempty"`
	RequiredVersions         *APIVersionsApplyConfiguration       `json:"requiredVersions,omitempty"`
	ExcludedFields           []APIExcludedFieldApplyConfiguration `json:"excludedFields,omitempty"`
}

// CompatibilitySchemaApplyConfiguration constructs a declarative configuration of the CompatibilitySchema type for use with
// apply.
func CompatibilitySchema() *CompatibilitySchemaApplyConfiguration {
	return &CompatibilitySchemaApplyConfiguration{}
}

// WithCustomResourceDefinition sets the CustomResourceDefinition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomResourceDefinition field is set to the value of the last call.
func (b *CompatibilitySchemaApplyConfiguration) WithCustomResourceDefinition(value *CRDDataApplyConfiguration) *CompatibilitySchemaApplyConfiguration {
	b.CustomResourceDefinition = value
	return b
}

// WithRequiredVersions sets the RequiredVersions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredVersions field is set to the value of the last call.
func (b *CompatibilitySchemaApplyConfiguration) WithRequiredVersions(value *APIVersionsApplyConfiguration) *CompatibilitySchemaApplyConfiguration {
	b.RequiredVersions = value
	return b
}

// WithExcludedFields adds the given value to the ExcludedFields field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExcludedFields field.
func (b *CompatibilitySchemaApplyConfiguration) WithExcludedFields(values ...*APIExcludedFieldApplyConfiguration) *CompatibilitySchemaApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExcludedFields")
		}
		b.ExcludedFields = append(b.ExcludedFields, *values[i])
	}
	return b
}
