// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1alpha1 "github.com/openshift/api/apiextensions/v1alpha1"
)

// CRDDataApplyConfiguration represents a declarative configuration of the CRDData type for use
// with apply.
//
// CRDData contains the complete definition of a CRD.
type CRDDataApplyConfiguration struct {
	// type indicates the type of the CRD data. The only supported type is "YAML".
	// This field is required.
	Type *apiextensionsv1alpha1.CRDDataType `json:"type,omitempty"`
	// data contains the complete definition of the CRD. This field must be in
	// the format specified by the type field. It may not be longer than 1572864
	// characters.
	// This field is required.
	Data *string `json:"data,omitempty"`
}

// CRDDataApplyConfiguration constructs a declarative configuration of the CRDData type for use with
// apply.
func CRDData() *CRDDataApplyConfiguration {
	return &CRDDataApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *CRDDataApplyConfiguration) WithType(value apiextensionsv1alpha1.CRDDataType) *CRDDataApplyConfiguration {
	b.Type = &value
	return b
}

// WithData sets the Data field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Data field is set to the value of the last call.
func (b *CRDDataApplyConfiguration) WithData(value string) *CRDDataApplyConfiguration {
	b.Data = &value
	return b
}
