// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EtcdBackupStoragePvcApplyConfiguration represents a declarative configuration of the EtcdBackupStoragePvc type for use
// with apply.
type EtcdBackupStoragePvcApplyConfiguration struct {
	// name is a reference to a PVC in the "openshift-etcd" namespace where the etcd backup file will be saved.
	// name must be between 1 and 253 characters and conform to RFC 1123 subdomain format:
	// lowercase alphanumeric characters, '-' or '.', starting and ending with alphanumeric characters.
	Name *string `json:"name,omitempty"`
	// path is a directory on the volume where the etcd backup file will be saved.
	// When present, path must be an absolute filepath between 1 and 2048 characters containing only alphanumeric characters, '/', '.', '_', or '-', starting with a '/'.
	Path *string `json:"path,omitempty"`
}

// EtcdBackupStoragePvcApplyConfiguration constructs a declarative configuration of the EtcdBackupStoragePvc type for use with
// apply.
func EtcdBackupStoragePvc() *EtcdBackupStoragePvcApplyConfiguration {
	return &EtcdBackupStoragePvcApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *EtcdBackupStoragePvcApplyConfiguration) WithName(value string) *EtcdBackupStoragePvcApplyConfiguration {
	b.Name = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *EtcdBackupStoragePvcApplyConfiguration) WithPath(value string) *EtcdBackupStoragePvcApplyConfiguration {
	b.Path = &value
	return b
}
