// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/api/operator/v1alpha1"
)

// EtcdBackupStorageApplyConfiguration represents a declarative configuration of the EtcdBackupStorage type for use
// with apply.
type EtcdBackupStorageApplyConfiguration struct {
	Type *operatorv1alpha1.EtcdBackupStorageType `json:"type,omitempty"`
	// pvc specifies the PersistentVolumeClaim (PVC) which binds a PersistentVolume where the etcd backup file will be saved.
	// The PVC must always be created in the "openshift-etcd" namespace.
	// This field is required when the storage type is "PVC"
	PVC *EtcdBackupStoragePvcApplyConfiguration `json:"pvc,omitempty"`
	// local specifies a host path directory on the master node where the etcd backup file will be saved.
	// This field is required when storage type is "Local"
	Local *EtcdBackupStorageLocalApplyConfiguration `json:"local,omitempty"`
}

// EtcdBackupStorageApplyConfiguration constructs a declarative configuration of the EtcdBackupStorage type for use with
// apply.
func EtcdBackupStorage() *EtcdBackupStorageApplyConfiguration {
	return &EtcdBackupStorageApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *EtcdBackupStorageApplyConfiguration) WithType(value operatorv1alpha1.EtcdBackupStorageType) *EtcdBackupStorageApplyConfiguration {
	b.Type = &value
	return b
}

// WithPVC sets the PVC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PVC field is set to the value of the last call.
func (b *EtcdBackupStorageApplyConfiguration) WithPVC(value *EtcdBackupStoragePvcApplyConfiguration) *EtcdBackupStorageApplyConfiguration {
	b.PVC = value
	return b
}

// WithLocal sets the Local field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Local field is set to the value of the last call.
func (b *EtcdBackupStorageApplyConfiguration) WithLocal(value *EtcdBackupStorageLocalApplyConfiguration) *EtcdBackupStorageApplyConfiguration {
	b.Local = value
	return b
}
