// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EtcdBackupPolicySpecApplyConfiguration represents a declarative configuration of the EtcdBackupPolicySpec type for use
// with apply.
type EtcdBackupPolicySpecApplyConfiguration struct {
	// schedule sets the backup schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.
	Schedule *string `json:"schedule,omitempty"`
	// timeZone name for the given schedule, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
	// If not specified, this will default to the time zone of the cluster-etcd-operator process.
	TimeZone *string `json:"timeZone,omitempty"`
	// nodeSelector specifies which master node(s) to run backup jobs on.
	// If no selector is specified, the default node-role.kubernetes.io/master label will be used.
	// If no nodes are matched, then no backups will run.
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// storage specifies the location where etcd backup files will be saved.
	Storage *EtcdBackupStorageApplyConfiguration `json:"storage,omitempty"`
	// retentionRules defines the policy for retaining and deleting existing backups.
	// Backups are deleted from the oldest first until all rules are satisfied.
	// If no rules are specified then backups created by this policy will not be automatically deleted.
	RetentionRules []EtcdBackupPolicyRetentionRuleApplyConfiguration `json:"retentionRules,omitempty"`
	// failedBackupsHistoryLimit defined the number of failed etcdbackups to retain. Value must be non-negative integer. Defaults to 1.
	FailedBackupsHistoryLimit *int `json:"failedBackupsHistoryLimit,omitempty"`
}

// EtcdBackupPolicySpecApplyConfiguration constructs a declarative configuration of the EtcdBackupPolicySpec type for use with
// apply.
func EtcdBackupPolicySpec() *EtcdBackupPolicySpecApplyConfiguration {
	return &EtcdBackupPolicySpecApplyConfiguration{}
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *EtcdBackupPolicySpecApplyConfiguration) WithSchedule(value string) *EtcdBackupPolicySpecApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithTimeZone sets the TimeZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeZone field is set to the value of the last call.
func (b *EtcdBackupPolicySpecApplyConfiguration) WithTimeZone(value string) *EtcdBackupPolicySpecApplyConfiguration {
	b.TimeZone = &value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *EtcdBackupPolicySpecApplyConfiguration) WithNodeSelector(entries map[string]string) *EtcdBackupPolicySpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *EtcdBackupPolicySpecApplyConfiguration) WithStorage(value *EtcdBackupStorageApplyConfiguration) *EtcdBackupPolicySpecApplyConfiguration {
	b.Storage = value
	return b
}

// WithRetentionRules adds the given value to the RetentionRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RetentionRules field.
func (b *EtcdBackupPolicySpecApplyConfiguration) WithRetentionRules(values ...*EtcdBackupPolicyRetentionRuleApplyConfiguration) *EtcdBackupPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRetentionRules")
		}
		b.RetentionRules = append(b.RetentionRules, *values[i])
	}
	return b
}

// WithFailedBackupsHistoryLimit sets the FailedBackupsHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedBackupsHistoryLimit field is set to the value of the last call.
func (b *EtcdBackupPolicySpecApplyConfiguration) WithFailedBackupsHistoryLimit(value int) *EtcdBackupPolicySpecApplyConfiguration {
	b.FailedBackupsHistoryLimit = &value
	return b
}
