// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/api/operator/v1alpha1"
	internal "github.com/openshift/client-go/operator/applyconfigurations/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// EtcdBackupPolicyApplyConfiguration represents a declarative configuration of the EtcdBackupPolicy type for use
// with apply.
//
// # EtcdBackupPolicy sets an automated schedule for taking backups of the etcd cluster
//
// Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
type EtcdBackupPolicyApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// spec holds user settable values for configuration
	Spec *EtcdBackupPolicySpecApplyConfiguration `json:"spec,omitempty"`
	// status holds observed values from the cluster. They may not be overridden.
	Status *EtcdBackupPolicyStatusApplyConfiguration `json:"status,omitempty"`
}

// EtcdBackupPolicy constructs a declarative configuration of the EtcdBackupPolicy type for use with
// apply.
func EtcdBackupPolicy(name string) *EtcdBackupPolicyApplyConfiguration {
	b := &EtcdBackupPolicyApplyConfiguration{}
	b.WithName(name)
	b.WithKind("EtcdBackupPolicy")
	b.WithAPIVersion("operator.openshift.io/v1alpha1")
	return b
}

// ExtractEtcdBackupPolicyFrom extracts the applied configuration owned by fieldManager from
// etcdBackupPolicy for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// etcdBackupPolicy must be a unmodified EtcdBackupPolicy API object that was retrieved from the Kubernetes API.
// ExtractEtcdBackupPolicyFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractEtcdBackupPolicyFrom(etcdBackupPolicy *operatorv1alpha1.EtcdBackupPolicy, fieldManager string, subresource string) (*EtcdBackupPolicyApplyConfiguration, error) {
	b := &EtcdBackupPolicyApplyConfiguration{}
	err := managedfields.ExtractInto(etcdBackupPolicy, internal.Parser().Type("com.github.openshift.api.operator.v1alpha1.EtcdBackupPolicy"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(etcdBackupPolicy.Name)

	b.WithKind("EtcdBackupPolicy")
	b.WithAPIVersion("operator.openshift.io/v1alpha1")
	return b, nil
}

// ExtractEtcdBackupPolicy extracts the applied configuration owned by fieldManager from
// etcdBackupPolicy. If no managedFields are found in etcdBackupPolicy for fieldManager, a
// EtcdBackupPolicyApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// etcdBackupPolicy must be a unmodified EtcdBackupPolicy API object that was retrieved from the Kubernetes API.
// ExtractEtcdBackupPolicy provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractEtcdBackupPolicy(etcdBackupPolicy *operatorv1alpha1.EtcdBackupPolicy, fieldManager string) (*EtcdBackupPolicyApplyConfiguration, error) {
	return ExtractEtcdBackupPolicyFrom(etcdBackupPolicy, fieldManager, "")
}

// ExtractEtcdBackupPolicyStatus extracts the applied configuration owned by fieldManager from
// etcdBackupPolicy for the status subresource.
func ExtractEtcdBackupPolicyStatus(etcdBackupPolicy *operatorv1alpha1.EtcdBackupPolicy, fieldManager string) (*EtcdBackupPolicyApplyConfiguration, error) {
	return ExtractEtcdBackupPolicyFrom(etcdBackupPolicy, fieldManager, "status")
}

func (b EtcdBackupPolicyApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithKind(value string) *EtcdBackupPolicyApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithAPIVersion(value string) *EtcdBackupPolicyApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithName(value string) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithGenerateName(value string) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithNamespace(value string) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithUID(value types.UID) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithResourceVersion(value string) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithGeneration(value int64) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithCreationTimestamp(value metav1.Time) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *EtcdBackupPolicyApplyConfiguration) WithLabels(entries map[string]string) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *EtcdBackupPolicyApplyConfiguration) WithAnnotations(entries map[string]string) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *EtcdBackupPolicyApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *EtcdBackupPolicyApplyConfiguration) WithFinalizers(values ...string) *EtcdBackupPolicyApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *EtcdBackupPolicyApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithSpec(value *EtcdBackupPolicySpecApplyConfiguration) *EtcdBackupPolicyApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *EtcdBackupPolicyApplyConfiguration) WithStatus(value *EtcdBackupPolicyStatusApplyConfiguration) *EtcdBackupPolicyApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *EtcdBackupPolicyApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *EtcdBackupPolicyApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *EtcdBackupPolicyApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *EtcdBackupPolicyApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
