// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/openshift/api/servicecertsigner/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// ServiceCertSignerOperatorConfigLister helps list ServiceCertSignerOperatorConfigs.
// All objects returned here must be treated as read-only.
type ServiceCertSignerOperatorConfigLister interface {
	// List lists all ServiceCertSignerOperatorConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ServiceCertSignerOperatorConfig, err error)
	// Get retrieves the ServiceCertSignerOperatorConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ServiceCertSignerOperatorConfig, error)
	ServiceCertSignerOperatorConfigListerExpansion
}

// serviceCertSignerOperatorConfigLister implements the ServiceCertSignerOperatorConfigLister interface.
type serviceCertSignerOperatorConfigLister struct {
	listers.ResourceIndexer[*v1alpha1.ServiceCertSignerOperatorConfig]
}

// NewServiceCertSignerOperatorConfigLister returns a new ServiceCertSignerOperatorConfigLister.
func NewServiceCertSignerOperatorConfigLister(indexer cache.Indexer) ServiceCertSignerOperatorConfigLister {
	return &serviceCertSignerOperatorConfigLister{listers.New[*v1alpha1.ServiceCertSignerOperatorConfig](indexer, v1alpha1.Resource("servicecertsigneroperatorconfig"))}
}
