// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apiauthorizationv1 "github.com/openshift/api/authorization/v1"
	internal "github.com/openshift/client-go/authorization/applyconfigurations/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// LocalSubjectAccessReviewApplyConfiguration represents a declarative configuration of the LocalSubjectAccessReview type for use
// with apply.
type LocalSubjectAccessReviewApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	ActionApplyConfiguration         `json:",inline"`
	User                             *string                            `json:"user,omitempty"`
	GroupsSlice                      []string                           `json:"groups,omitempty"`
	Scopes                           *apiauthorizationv1.OptionalScopes `json:"scopes,omitempty"`
}

// LocalSubjectAccessReview constructs a declarative configuration of the LocalSubjectAccessReview type for use with
// apply.
func LocalSubjectAccessReview(name, namespace string) *LocalSubjectAccessReviewApplyConfiguration {
	b := &LocalSubjectAccessReviewApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("LocalSubjectAccessReview")
	b.WithAPIVersion("authorization.openshift.io/v1")
	return b
}

// ExtractLocalSubjectAccessReview extracts the applied configuration owned by fieldManager from
// localSubjectAccessReview. If no managedFields are found in localSubjectAccessReview for fieldManager, a
// LocalSubjectAccessReviewApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// localSubjectAccessReview must be a unmodified LocalSubjectAccessReview API object that was retrieved from the Kubernetes API.
// ExtractLocalSubjectAccessReview provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
// Experimental!
func ExtractLocalSubjectAccessReview(localSubjectAccessReview *apiauthorizationv1.LocalSubjectAccessReview, fieldManager string) (*LocalSubjectAccessReviewApplyConfiguration, error) {
	return extractLocalSubjectAccessReview(localSubjectAccessReview, fieldManager, "")
}

// ExtractLocalSubjectAccessReviewStatus is the same as ExtractLocalSubjectAccessReview except
// that it extracts the status subresource applied configuration.
// Experimental!
func ExtractLocalSubjectAccessReviewStatus(localSubjectAccessReview *apiauthorizationv1.LocalSubjectAccessReview, fieldManager string) (*LocalSubjectAccessReviewApplyConfiguration, error) {
	return extractLocalSubjectAccessReview(localSubjectAccessReview, fieldManager, "status")
}

func extractLocalSubjectAccessReview(localSubjectAccessReview *apiauthorizationv1.LocalSubjectAccessReview, fieldManager string, subresource string) (*LocalSubjectAccessReviewApplyConfiguration, error) {
	b := &LocalSubjectAccessReviewApplyConfiguration{}
	err := managedfields.ExtractInto(localSubjectAccessReview, internal.Parser().Type("com.github.openshift.api.authorization.v1.LocalSubjectAccessReview"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(localSubjectAccessReview.Name)
	b.WithNamespace(localSubjectAccessReview.Namespace)

	b.WithKind("LocalSubjectAccessReview")
	b.WithAPIVersion("authorization.openshift.io/v1")
	return b, nil
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithKind(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithAPIVersion(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithName(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithGenerateName(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithNamespace(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithUID(value types.UID) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithResourceVersion(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithGeneration(value int64) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithCreationTimestamp(value metav1.Time) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithLabels(entries map[string]string) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithAnnotations(entries map[string]string) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.OwnerReferences = append(b.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithFinalizers(values ...string) *LocalSubjectAccessReviewApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.Finalizers = append(b.Finalizers, values[i])
	}
	return b
}

func (b *LocalSubjectAccessReviewApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithNamespace(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithVerb sets the Verb field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Verb field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithVerb(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.Verb = &value
	return b
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithGroup(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.Group = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithVersion(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.Version = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithResource(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.Resource = &value
	return b
}

// WithResourceName sets the ResourceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceName field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithResourceName(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.ResourceName = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithPath(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.Path = &value
	return b
}

// WithIsNonResourceURL sets the IsNonResourceURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsNonResourceURL field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithIsNonResourceURL(value bool) *LocalSubjectAccessReviewApplyConfiguration {
	b.IsNonResourceURL = &value
	return b
}

// WithContent sets the Content field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Content field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithContent(value runtime.RawExtension) *LocalSubjectAccessReviewApplyConfiguration {
	b.Content = &value
	return b
}

// WithUser sets the User field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the User field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithUser(value string) *LocalSubjectAccessReviewApplyConfiguration {
	b.User = &value
	return b
}

// WithGroupsSlice adds the given value to the GroupsSlice field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the GroupsSlice field.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithGroupsSlice(values ...string) *LocalSubjectAccessReviewApplyConfiguration {
	for i := range values {
		b.GroupsSlice = append(b.GroupsSlice, values[i])
	}
	return b
}

// WithScopes sets the Scopes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scopes field is set to the value of the last call.
func (b *LocalSubjectAccessReviewApplyConfiguration) WithScopes(value apiauthorizationv1.OptionalScopes) *LocalSubjectAccessReviewApplyConfiguration {
	b.Scopes = &value
	return b
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *LocalSubjectAccessReviewApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.Name
}
