// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/openshift/api/network/v1"
	networkv1 "github.com/openshift/client-go/network/applyconfigurations/network/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetNamespaces implements NetNamespaceInterface
type FakeNetNamespaces struct {
	Fake *FakeNetworkV1
}

var netnamespacesResource = v1.SchemeGroupVersion.WithResource("netnamespaces")

var netnamespacesKind = v1.SchemeGroupVersion.WithKind("NetNamespace")

// Get takes name of the netNamespace, and returns the corresponding netNamespace object, and an error if there is any.
func (c *FakeNetNamespaces) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NetNamespace, err error) {
	emptyResult := &v1.NetNamespace{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(netnamespacesResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetNamespace), err
}

// List takes label and field selectors, and returns the list of NetNamespaces that match those selectors.
func (c *FakeNetNamespaces) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NetNamespaceList, err error) {
	emptyResult := &v1.NetNamespaceList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(netnamespacesResource, netnamespacesKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.NetNamespaceList{ListMeta: obj.(*v1.NetNamespaceList).ListMeta}
	for _, item := range obj.(*v1.NetNamespaceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested netNamespaces.
func (c *FakeNetNamespaces) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(netnamespacesResource, opts))
}

// Create takes the representation of a netNamespace and creates it.  Returns the server's representation of the netNamespace, and an error, if there is any.
func (c *FakeNetNamespaces) Create(ctx context.Context, netNamespace *v1.NetNamespace, opts metav1.CreateOptions) (result *v1.NetNamespace, err error) {
	emptyResult := &v1.NetNamespace{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(netnamespacesResource, netNamespace, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetNamespace), err
}

// Update takes the representation of a netNamespace and updates it. Returns the server's representation of the netNamespace, and an error, if there is any.
func (c *FakeNetNamespaces) Update(ctx context.Context, netNamespace *v1.NetNamespace, opts metav1.UpdateOptions) (result *v1.NetNamespace, err error) {
	emptyResult := &v1.NetNamespace{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(netnamespacesResource, netNamespace, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetNamespace), err
}

// Delete takes name of the netNamespace and deletes it. Returns an error if one occurs.
func (c *FakeNetNamespaces) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(netnamespacesResource, name, opts), &v1.NetNamespace{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetNamespaces) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(netnamespacesResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.NetNamespaceList{})
	return err
}

// Patch applies the patch and returns the patched netNamespace.
func (c *FakeNetNamespaces) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NetNamespace, err error) {
	emptyResult := &v1.NetNamespace{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(netnamespacesResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetNamespace), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied netNamespace.
func (c *FakeNetNamespaces) Apply(ctx context.Context, netNamespace *networkv1.NetNamespaceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.NetNamespace, err error) {
	if netNamespace == nil {
		return nil, fmt.Errorf("netNamespace provided to Apply must not be nil")
	}
	data, err := json.Marshal(netNamespace)
	if err != nil {
		return nil, err
	}
	name := netNamespace.Name
	if name == nil {
		return nil, fmt.Errorf("netNamespace.Name must be provided to Apply")
	}
	emptyResult := &v1.NetNamespace{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(netnamespacesResource, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.NetNamespace), err
}
