// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apioperatorv1alpha1 "github.com/openshift/api/operator/v1alpha1"
	versioned "github.com/openshift/client-go/operator/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/operator/informers/externalversions/internalinterfaces"
	operatorv1alpha1 "github.com/openshift/client-go/operator/listers/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterVersionOperatorInformer provides access to a shared informer and lister for
// ClusterVersionOperators. Prefer using the type-safe variant (see [TypedClusterVersionOperatorInformer]).
type ClusterVersionOperatorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1alpha1.ClusterVersionOperatorLister
}

// TypedClusterVersionOperatorInformer provides access to a shared informer and lister for
// ClusterVersionOperators, including the type-safe TypedInformer variant.
// It is a superset of ClusterVersionOperatorInformer.
type TypedClusterVersionOperatorInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() ClusterVersionOperatorIndexInformer
	Lister() operatorv1alpha1.ClusterVersionOperatorLister
}

// ClusterVersionOperatorIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type ClusterVersionOperatorIndexInformer cache.TypedSharedIndexInformer[*apioperatorv1alpha1.ClusterVersionOperator]

// ClusterVersionOperatorHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for ClusterVersionOperator.
type ClusterVersionOperatorHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apioperatorv1alpha1.ClusterVersionOperator]

// ClusterVersionOperatorDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for ClusterVersionOperator.
type ClusterVersionOperatorDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apioperatorv1alpha1.ClusterVersionOperator]

// ClusterVersionOperatorFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for ClusterVersionOperator.
type ClusterVersionOperatorFilteringHandler = cache.TypedFilteringResourceEventHandler[*apioperatorv1alpha1.ClusterVersionOperator]

// ClusterVersionOperatorIndexers is a specialization of [cache.TypedIndexers] for ClusterVersionOperator.
type ClusterVersionOperatorIndexers = cache.TypedIndexers[*apioperatorv1alpha1.ClusterVersionOperator]

// DeletedClusterVersionOperator is a specialization of [cache.DeletedObject] for ClusterVersionOperator.
type DeletedClusterVersionOperator = cache.DeletedObject[*apioperatorv1alpha1.ClusterVersionOperator]

type clusterVersionOperatorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterVersionOperatorInformer constructs a new informer for ClusterVersionOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterVersionOperatorInformer]).
func NewClusterVersionOperatorInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewClusterVersionOperatorInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedClusterVersionOperatorInformer constructs a new informer for ClusterVersionOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterVersionOperatorInformer(client versioned.Interface, resyncPeriod time.Duration, indexers ClusterVersionOperatorIndexers) ClusterVersionOperatorIndexInformer {
	return NewTypedClusterVersionOperatorInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredClusterVersionOperatorInformer constructs a new informer for ClusterVersionOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredClusterVersionOperatorInformer]).
func NewFilteredClusterVersionOperatorInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedClusterVersionOperatorInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredClusterVersionOperatorInformer constructs a new informer for ClusterVersionOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredClusterVersionOperatorInformer(client versioned.Interface, resyncPeriod time.Duration, indexers ClusterVersionOperatorIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) ClusterVersionOperatorIndexInformer {
	return NewTypedClusterVersionOperatorInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewClusterVersionOperatorInformerWithOptions constructs a new informer for ClusterVersionOperator type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterVersionOperatorInformerWithOptions]).
func NewClusterVersionOperatorInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedClusterVersionOperatorInformerWithOptions(client, options)
}

// NewTypedClusterVersionOperatorInformerWithOptions constructs a new informer for ClusterVersionOperator type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterVersionOperatorInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) ClusterVersionOperatorIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator.openshift.io", Version: "v1alpha1", Resource: "clusterversionoperators"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apioperatorv1alpha1.ClusterVersionOperator](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().ClusterVersionOperators().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().ClusterVersionOperators().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().ClusterVersionOperators().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().ClusterVersionOperators().Watch(ctx, opts)
			},
		}, client),
		&apioperatorv1alpha1.ClusterVersionOperator{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *clusterVersionOperatorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedClusterVersionOperatorInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *clusterVersionOperatorInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *clusterVersionOperatorInformer) TypedInformer() ClusterVersionOperatorIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1alpha1.ClusterVersionOperator](f.factory.InformerFor(&apioperatorv1alpha1.ClusterVersionOperator{}, f.defaultInformer))
}

func (f *clusterVersionOperatorInformer) Lister() operatorv1alpha1.ClusterVersionOperatorLister {
	return operatorv1alpha1.NewClusterVersionOperatorLister(f.Informer().GetIndexer())
}

// ToTypedClusterVersionOperatorInformer converts an untyped informer into a TypedClusterVersionOperatorInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ClusterVersionOperator. If that is not the case, calling type-safe methods of the returned
// TypedClusterVersionOperatorInformer leads to runtime panics. A safer alternative is to pass
// around a TypedClusterVersionOperatorInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedClusterVersionOperatorInformer(informer ClusterVersionOperatorInformer) TypedClusterVersionOperatorInformer {
	if informer, ok := informer.(TypedClusterVersionOperatorInformer); ok {
		return informer
	}
	return &clusterVersionOperatorTypedInformerAdapter{informer}
}

type clusterVersionOperatorTypedInformerAdapter struct {
	ClusterVersionOperatorInformer
}

func (a *clusterVersionOperatorTypedInformerAdapter) TypedInformer() ClusterVersionOperatorIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1alpha1.ClusterVersionOperator](a.Informer())
}

// ToClusterVersionOperatorIndexInformer converts an untyped informer into a ClusterVersionOperatorIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ClusterVersionOperator. If that is not the case, calling type-safe methods of the returned
// ClusterVersionOperatorIndexInformer leads to runtime panics. A safer alternative is to pass
// around a ClusterVersionOperatorIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToClusterVersionOperatorIndexInformer(informer cache.SharedIndexInformer) ClusterVersionOperatorIndexInformer {
	if informer, ok := informer.(ClusterVersionOperatorIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apioperatorv1alpha1.ClusterVersionOperator](informer)
}
