// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apioperatorv1alpha1 "github.com/openshift/api/operator/v1alpha1"
	versioned "github.com/openshift/client-go/operator/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/operator/informers/externalversions/internalinterfaces"
	operatorv1alpha1 "github.com/openshift/client-go/operator/listers/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdBackupPolicyInformer provides access to a shared informer and lister for
// EtcdBackupPolicies. Prefer using the type-safe variant (see [TypedEtcdBackupPolicyInformer]).
type EtcdBackupPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1alpha1.EtcdBackupPolicyLister
}

// TypedEtcdBackupPolicyInformer provides access to a shared informer and lister for
// EtcdBackupPolicies, including the type-safe TypedInformer variant.
// It is a superset of EtcdBackupPolicyInformer.
type TypedEtcdBackupPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() EtcdBackupPolicyIndexInformer
	Lister() operatorv1alpha1.EtcdBackupPolicyLister
}

// EtcdBackupPolicyIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type EtcdBackupPolicyIndexInformer cache.TypedSharedIndexInformer[*apioperatorv1alpha1.EtcdBackupPolicy]

// EtcdBackupPolicyHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for EtcdBackupPolicy.
type EtcdBackupPolicyHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apioperatorv1alpha1.EtcdBackupPolicy]

// EtcdBackupPolicyDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for EtcdBackupPolicy.
type EtcdBackupPolicyDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apioperatorv1alpha1.EtcdBackupPolicy]

// EtcdBackupPolicyFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for EtcdBackupPolicy.
type EtcdBackupPolicyFilteringHandler = cache.TypedFilteringResourceEventHandler[*apioperatorv1alpha1.EtcdBackupPolicy]

// EtcdBackupPolicyIndexers is a specialization of [cache.TypedIndexers] for EtcdBackupPolicy.
type EtcdBackupPolicyIndexers = cache.TypedIndexers[*apioperatorv1alpha1.EtcdBackupPolicy]

// DeletedEtcdBackupPolicy is a specialization of [cache.DeletedObject] for EtcdBackupPolicy.
type DeletedEtcdBackupPolicy = cache.DeletedObject[*apioperatorv1alpha1.EtcdBackupPolicy]

type etcdBackupPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewEtcdBackupPolicyInformer constructs a new informer for EtcdBackupPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedEtcdBackupPolicyInformer]).
func NewEtcdBackupPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewEtcdBackupPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedEtcdBackupPolicyInformer constructs a new informer for EtcdBackupPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedEtcdBackupPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers EtcdBackupPolicyIndexers) EtcdBackupPolicyIndexInformer {
	return NewTypedEtcdBackupPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredEtcdBackupPolicyInformer constructs a new informer for EtcdBackupPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredEtcdBackupPolicyInformer]).
func NewFilteredEtcdBackupPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedEtcdBackupPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredEtcdBackupPolicyInformer constructs a new informer for EtcdBackupPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredEtcdBackupPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers EtcdBackupPolicyIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) EtcdBackupPolicyIndexInformer {
	return NewTypedEtcdBackupPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewEtcdBackupPolicyInformerWithOptions constructs a new informer for EtcdBackupPolicy type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedEtcdBackupPolicyInformerWithOptions]).
func NewEtcdBackupPolicyInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedEtcdBackupPolicyInformerWithOptions(client, options)
}

// NewTypedEtcdBackupPolicyInformerWithOptions constructs a new informer for EtcdBackupPolicy type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedEtcdBackupPolicyInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) EtcdBackupPolicyIndexInformer {
	gvr := schema.GroupVersionResource{Group: "operator.openshift.io", Version: "v1alpha1", Resource: "etcdbackuppolicys"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apioperatorv1alpha1.EtcdBackupPolicy](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().EtcdBackupPolicies().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().EtcdBackupPolicies().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().EtcdBackupPolicies().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.OperatorV1alpha1().EtcdBackupPolicies().Watch(ctx, opts)
			},
		}, client),
		&apioperatorv1alpha1.EtcdBackupPolicy{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *etcdBackupPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedEtcdBackupPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *etcdBackupPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *etcdBackupPolicyInformer) TypedInformer() EtcdBackupPolicyIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1alpha1.EtcdBackupPolicy](f.factory.InformerFor(&apioperatorv1alpha1.EtcdBackupPolicy{}, f.defaultInformer))
}

func (f *etcdBackupPolicyInformer) Lister() operatorv1alpha1.EtcdBackupPolicyLister {
	return operatorv1alpha1.NewEtcdBackupPolicyLister(f.Informer().GetIndexer())
}

// ToTypedEtcdBackupPolicyInformer converts an untyped informer into a TypedEtcdBackupPolicyInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *EtcdBackupPolicy. If that is not the case, calling type-safe methods of the returned
// TypedEtcdBackupPolicyInformer leads to runtime panics. A safer alternative is to pass
// around a TypedEtcdBackupPolicyInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedEtcdBackupPolicyInformer(informer EtcdBackupPolicyInformer) TypedEtcdBackupPolicyInformer {
	if informer, ok := informer.(TypedEtcdBackupPolicyInformer); ok {
		return informer
	}
	return &etcdBackupPolicyTypedInformerAdapter{informer}
}

type etcdBackupPolicyTypedInformerAdapter struct {
	EtcdBackupPolicyInformer
}

func (a *etcdBackupPolicyTypedInformerAdapter) TypedInformer() EtcdBackupPolicyIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apioperatorv1alpha1.EtcdBackupPolicy](a.Informer())
}

// ToEtcdBackupPolicyIndexInformer converts an untyped informer into a EtcdBackupPolicyIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *EtcdBackupPolicy. If that is not the case, calling type-safe methods of the returned
// EtcdBackupPolicyIndexInformer leads to runtime panics. A safer alternative is to pass
// around a EtcdBackupPolicyIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToEtcdBackupPolicyIndexInformer(informer cache.SharedIndexInformer) EtcdBackupPolicyIndexInformer {
	if informer, ok := informer.(EtcdBackupPolicyIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apioperatorv1alpha1.EtcdBackupPolicy](informer)
}
