// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apiinsightsv1 "github.com/openshift/api/insights/v1"
	versioned "github.com/openshift/client-go/insights/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/insights/informers/externalversions/internalinterfaces"
	insightsv1 "github.com/openshift/client-go/insights/listers/insights/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DataGatherInformer provides access to a shared informer and lister for
// DataGathers.
type DataGatherInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() insightsv1.DataGatherLister
}

type dataGatherInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDataGatherInformer constructs a new informer for DataGather type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDataGatherInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDataGatherInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDataGatherInformer constructs a new informer for DataGather type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDataGatherInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InsightsV1().DataGathers().List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InsightsV1().DataGathers().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InsightsV1().DataGathers().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InsightsV1().DataGathers().Watch(ctx, options)
			},
		},
		&apiinsightsv1.DataGather{},
		resyncPeriod,
		indexers,
	)
}

func (f *dataGatherInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDataGatherInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dataGatherInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiinsightsv1.DataGather{}, f.defaultInformer)
}

func (f *dataGatherInformer) Lister() insightsv1.DataGatherLister {
	return insightsv1.NewDataGatherLister(f.Informer().GetIndexer())
}
