// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	configv1alpha1 "github.com/openshift/api/config/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ControllerManagerLister helps list ControllerManagers.
// All objects returned here must be treated as read-only.
type ControllerManagerLister interface {
	// List lists all ControllerManagers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*configv1alpha1.ControllerManager, err error)
	// Get retrieves the ControllerManager from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*configv1alpha1.ControllerManager, error)
	ControllerManagerListerExpansion
}

// controllerManagerLister implements the ControllerManagerLister interface.
type controllerManagerLister struct {
	listers.ResourceIndexer[*configv1alpha1.ControllerManager]
}

// NewControllerManagerLister returns a new ControllerManagerLister.
func NewControllerManagerLister(indexer cache.Indexer) ControllerManagerLister {
	return &controllerManagerLister{listers.New[*configv1alpha1.ControllerManager](indexer, configv1alpha1.Resource("controllermanager"))}
}
