// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	etcdv1 "github.com/openshift/api/etcd/v1"
	versioned "github.com/openshift/client-go/etcd/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/etcd/informers/externalversions/internalinterfaces"
	v1 "github.com/openshift/client-go/etcd/listers/etcd/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterMemberRequestInformer provides access to a shared informer and lister for
// ClusterMemberRequests.
type ClusterMemberRequestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ClusterMemberRequestLister
}

type clusterMemberRequestInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterMemberRequestInformer constructs a new informer for ClusterMemberRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterMemberRequestInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterMemberRequestInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterMemberRequestInformer constructs a new informer for ClusterMemberRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterMemberRequestInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EtcdV1().ClusterMemberRequests().List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EtcdV1().ClusterMemberRequests().Watch(options)
			},
		},
		&etcdv1.ClusterMemberRequest{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterMemberRequestInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterMemberRequestInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterMemberRequestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&etcdv1.ClusterMemberRequest{}, f.defaultInformer)
}

func (f *clusterMemberRequestInformer) Lister() v1.ClusterMemberRequestLister {
	return v1.NewClusterMemberRequestLister(f.Informer().GetIndexer())
}
