// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apimonitoringv1 "github.com/openshift/api/monitoring/v1"
	versioned "github.com/openshift/client-go/monitoring/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/monitoring/informers/externalversions/internalinterfaces"
	monitoringv1 "github.com/openshift/client-go/monitoring/listers/monitoring/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AlertingRuleInformer provides access to a shared informer and lister for
// AlertingRules.
type AlertingRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() monitoringv1.AlertingRuleLister
}

type alertingRuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAlertingRuleInformer constructs a new informer for AlertingRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAlertingRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAlertingRuleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAlertingRuleInformer constructs a new informer for AlertingRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAlertingRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1().AlertingRules(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1().AlertingRules(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1().AlertingRules(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1().AlertingRules(namespace).Watch(ctx, options)
			},
		},
		&apimonitoringv1.AlertingRule{},
		resyncPeriod,
		indexers,
	)
}

func (f *alertingRuleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAlertingRuleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *alertingRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apimonitoringv1.AlertingRule{}, f.defaultInformer)
}

func (f *alertingRuleInformer) Lister() monitoringv1.AlertingRuleLister {
	return monitoringv1.NewAlertingRuleLister(f.Informer().GetIndexer())
}
