// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// GathererStatusApplyConfiguration represents a declarative configuration of the GathererStatus type for use
// with apply.
type GathererStatusApplyConfiguration struct {
	Conditions        []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	Name              *string                              `json:"name,omitempty"`
	LastGatherSeconds *int32                               `json:"lastGatherSeconds,omitempty"`
}

// GathererStatusApplyConfiguration constructs a declarative configuration of the GathererStatus type for use with
// apply.
func GathererStatus() *GathererStatusApplyConfiguration {
	return &GathererStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *GathererStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *GathererStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *GathererStatusApplyConfiguration) WithName(value string) *GathererStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithLastGatherSeconds sets the LastGatherSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastGatherSeconds field is set to the value of the last call.
func (b *GathererStatusApplyConfiguration) WithLastGatherSeconds(value int32) *GathererStatusApplyConfiguration {
	b.LastGatherSeconds = &value
	return b
}
