// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/openshift/client-go/apiserver/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// APIRequestCounts returns a APIRequestCountInformer.
	APIRequestCounts() APIRequestCountInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// APIRequestCounts returns a APIRequestCountInformer.
func (v *version) APIRequestCounts() APIRequestCountInformer {
	return &aPIRequestCountInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
