// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/openshift/api/config/v1"
	scheme "github.com/openshift/client-go/config/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DeschedulersGetter has a method to return a DeschedulerInterface.
// A group's client should implement this interface.
type DeschedulersGetter interface {
	Deschedulers() DeschedulerInterface
}

// DeschedulerInterface has methods to work with Descheduler resources.
type DeschedulerInterface interface {
	Create(ctx context.Context, descheduler *v1.Descheduler, opts metav1.CreateOptions) (*v1.Descheduler, error)
	Update(ctx context.Context, descheduler *v1.Descheduler, opts metav1.UpdateOptions) (*v1.Descheduler, error)
	UpdateStatus(ctx context.Context, descheduler *v1.Descheduler, opts metav1.UpdateOptions) (*v1.Descheduler, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Descheduler, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DeschedulerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Descheduler, err error)
	DeschedulerExpansion
}

// deschedulers implements DeschedulerInterface
type deschedulers struct {
	client rest.Interface
}

// newDeschedulers returns a Deschedulers
func newDeschedulers(c *ConfigV1Client) *deschedulers {
	return &deschedulers{
		client: c.RESTClient(),
	}
}

// Get takes name of the descheduler, and returns the corresponding descheduler object, and an error if there is any.
func (c *deschedulers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Descheduler, err error) {
	result = &v1.Descheduler{}
	err = c.client.Get().
		Resource("deschedulers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Deschedulers that match those selectors.
func (c *deschedulers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DeschedulerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DeschedulerList{}
	err = c.client.Get().
		Resource("deschedulers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested deschedulers.
func (c *deschedulers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("deschedulers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a descheduler and creates it.  Returns the server's representation of the descheduler, and an error, if there is any.
func (c *deschedulers) Create(ctx context.Context, descheduler *v1.Descheduler, opts metav1.CreateOptions) (result *v1.Descheduler, err error) {
	result = &v1.Descheduler{}
	err = c.client.Post().
		Resource("deschedulers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(descheduler).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a descheduler and updates it. Returns the server's representation of the descheduler, and an error, if there is any.
func (c *deschedulers) Update(ctx context.Context, descheduler *v1.Descheduler, opts metav1.UpdateOptions) (result *v1.Descheduler, err error) {
	result = &v1.Descheduler{}
	err = c.client.Put().
		Resource("deschedulers").
		Name(descheduler.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(descheduler).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *deschedulers) UpdateStatus(ctx context.Context, descheduler *v1.Descheduler, opts metav1.UpdateOptions) (result *v1.Descheduler, err error) {
	result = &v1.Descheduler{}
	err = c.client.Put().
		Resource("deschedulers").
		Name(descheduler.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(descheduler).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the descheduler and deletes it. Returns an error if one occurs.
func (c *deschedulers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("deschedulers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *deschedulers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("deschedulers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched descheduler.
func (c *deschedulers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Descheduler, err error) {
	result = &v1.Descheduler{}
	err = c.client.Patch(pt).
		Resource("deschedulers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
