// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/openshift/api/sharedresource/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// SharedSecretLister helps list SharedSecrets.
// All objects returned here must be treated as read-only.
type SharedSecretLister interface {
	// List lists all SharedSecrets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.SharedSecret, err error)
	// Get retrieves the SharedSecret from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.SharedSecret, error)
	SharedSecretListerExpansion
}

// sharedSecretLister implements the SharedSecretLister interface.
type sharedSecretLister struct {
	listers.ResourceIndexer[*v1alpha1.SharedSecret]
}

// NewSharedSecretLister returns a new SharedSecretLister.
func NewSharedSecretLister(indexer cache.Indexer) SharedSecretLister {
	return &sharedSecretLister{listers.New[*v1alpha1.SharedSecret](indexer, v1alpha1.Resource("sharedsecret"))}
}
