// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiapiextensionsv1alpha1 "github.com/openshift/api/apiextensions/v1alpha1"
	versioned "github.com/openshift/client-go/apiextensions/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/apiextensions/informers/externalversions/internalinterfaces"
	apiextensionsv1alpha1 "github.com/openshift/client-go/apiextensions/listers/apiextensions/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CompatibilityRequirementInformer provides access to a shared informer and lister for
// CompatibilityRequirements.
type CompatibilityRequirementInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiextensionsv1alpha1.CompatibilityRequirementLister
}

type compatibilityRequirementInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCompatibilityRequirementInformer constructs a new informer for CompatibilityRequirement type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompatibilityRequirementInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewCompatibilityRequirementInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewFilteredCompatibilityRequirementInformer constructs a new informer for CompatibilityRequirement type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCompatibilityRequirementInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewCompatibilityRequirementInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewCompatibilityRequirementInformerWithOptions constructs a new informer for CompatibilityRequirement type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCompatibilityRequirementInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	gvr := schema.GroupVersionResource{Group: "apiextensions.openshift.io", Version: "v1alpha1", Resource: "compatibilityrequirements"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ApiextensionsV1alpha1().CompatibilityRequirements().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ApiextensionsV1alpha1().CompatibilityRequirements().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ApiextensionsV1alpha1().CompatibilityRequirements().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ApiextensionsV1alpha1().CompatibilityRequirements().Watch(ctx, opts)
			},
		}, client),
		&apiapiextensionsv1alpha1.CompatibilityRequirement{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	)
}

func (f *compatibilityRequirementInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewCompatibilityRequirementInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *compatibilityRequirementInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiapiextensionsv1alpha1.CompatibilityRequirement{}, f.defaultInformer)
}

func (f *compatibilityRequirementInformer) Lister() apiextensionsv1alpha1.CompatibilityRequirementLister {
	return apiextensionsv1alpha1.NewCompatibilityRequirementLister(f.Informer().GetIndexer())
}
