// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisharedresourcev1alpha1 "github.com/openshift/api/sharedresource/v1alpha1"
	versioned "github.com/openshift/client-go/sharedresource/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/sharedresource/informers/externalversions/internalinterfaces"
	sharedresourcev1alpha1 "github.com/openshift/client-go/sharedresource/listers/sharedresource/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SharedConfigMapInformer provides access to a shared informer and lister for
// SharedConfigMaps. Prefer using the type-safe variant (see [TypedSharedConfigMapInformer]).
type SharedConfigMapInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() sharedresourcev1alpha1.SharedConfigMapLister
}

// TypedSharedConfigMapInformer provides access to a shared informer and lister for
// SharedConfigMaps, including the type-safe TypedInformer variant.
// It is a superset of SharedConfigMapInformer.
type TypedSharedConfigMapInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() SharedConfigMapIndexInformer
	Lister() sharedresourcev1alpha1.SharedConfigMapLister
}

// SharedConfigMapIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type SharedConfigMapIndexInformer cache.TypedSharedIndexInformer[*apisharedresourcev1alpha1.SharedConfigMap]

// SharedConfigMapHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for SharedConfigMap.
type SharedConfigMapHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisharedresourcev1alpha1.SharedConfigMap]

// SharedConfigMapDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for SharedConfigMap.
type SharedConfigMapDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisharedresourcev1alpha1.SharedConfigMap]

// SharedConfigMapFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for SharedConfigMap.
type SharedConfigMapFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisharedresourcev1alpha1.SharedConfigMap]

// SharedConfigMapIndexers is a specialization of [cache.TypedIndexers] for SharedConfigMap.
type SharedConfigMapIndexers = cache.TypedIndexers[*apisharedresourcev1alpha1.SharedConfigMap]

// DeletedSharedConfigMap is a specialization of [cache.DeletedObject] for SharedConfigMap.
type DeletedSharedConfigMap = cache.DeletedObject[*apisharedresourcev1alpha1.SharedConfigMap]

type sharedConfigMapInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSharedConfigMapInformer constructs a new informer for SharedConfigMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSharedConfigMapInformer]).
func NewSharedConfigMapInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewSharedConfigMapInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedSharedConfigMapInformer constructs a new informer for SharedConfigMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSharedConfigMapInformer(client versioned.Interface, resyncPeriod time.Duration, indexers SharedConfigMapIndexers) SharedConfigMapIndexInformer {
	return NewTypedSharedConfigMapInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredSharedConfigMapInformer constructs a new informer for SharedConfigMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredSharedConfigMapInformer]).
func NewFilteredSharedConfigMapInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedSharedConfigMapInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredSharedConfigMapInformer constructs a new informer for SharedConfigMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredSharedConfigMapInformer(client versioned.Interface, resyncPeriod time.Duration, indexers SharedConfigMapIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) SharedConfigMapIndexInformer {
	return NewTypedSharedConfigMapInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewSharedConfigMapInformerWithOptions constructs a new informer for SharedConfigMap type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSharedConfigMapInformerWithOptions]).
func NewSharedConfigMapInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedSharedConfigMapInformerWithOptions(client, options)
}

// NewTypedSharedConfigMapInformerWithOptions constructs a new informer for SharedConfigMap type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSharedConfigMapInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) SharedConfigMapIndexInformer {
	gvr := schema.GroupVersionResource{Group: "sharedresource.openshift.io", Version: "v1alpha1", Resource: "sharedconfigmaps"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisharedresourcev1alpha1.SharedConfigMap](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SharedresourceV1alpha1().SharedConfigMaps().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SharedresourceV1alpha1().SharedConfigMaps().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SharedresourceV1alpha1().SharedConfigMaps().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SharedresourceV1alpha1().SharedConfigMaps().Watch(ctx, opts)
			},
		}, client),
		&apisharedresourcev1alpha1.SharedConfigMap{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *sharedConfigMapInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedSharedConfigMapInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *sharedConfigMapInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *sharedConfigMapInformer) TypedInformer() SharedConfigMapIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisharedresourcev1alpha1.SharedConfigMap](f.factory.InformerFor(&apisharedresourcev1alpha1.SharedConfigMap{}, f.defaultInformer))
}

func (f *sharedConfigMapInformer) Lister() sharedresourcev1alpha1.SharedConfigMapLister {
	return sharedresourcev1alpha1.NewSharedConfigMapLister(f.Informer().GetIndexer())
}

// ToTypedSharedConfigMapInformer converts an untyped informer into a TypedSharedConfigMapInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *SharedConfigMap. If that is not the case, calling type-safe methods of the returned
// TypedSharedConfigMapInformer leads to runtime panics. A safer alternative is to pass
// around a TypedSharedConfigMapInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedSharedConfigMapInformer(informer SharedConfigMapInformer) TypedSharedConfigMapInformer {
	if informer, ok := informer.(TypedSharedConfigMapInformer); ok {
		return informer
	}
	return &sharedConfigMapTypedInformerAdapter{informer}
}

type sharedConfigMapTypedInformerAdapter struct {
	SharedConfigMapInformer
}

func (a *sharedConfigMapTypedInformerAdapter) TypedInformer() SharedConfigMapIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisharedresourcev1alpha1.SharedConfigMap](a.Informer())
}

// ToSharedConfigMapIndexInformer converts an untyped informer into a SharedConfigMapIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *SharedConfigMap. If that is not the case, calling type-safe methods of the returned
// SharedConfigMapIndexInformer leads to runtime panics. A safer alternative is to pass
// around a SharedConfigMapIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToSharedConfigMapIndexInformer(informer cache.SharedIndexInformer) SharedConfigMapIndexInformer {
	if informer, ok := informer.(SharedConfigMapIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisharedresourcev1alpha1.SharedConfigMap](informer)
}
