// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/openshift/client-go/monitoring/clientset/versioned/typed/monitoring/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMonitoringV1 struct {
	*testing.Fake
}

func (c *FakeMonitoringV1) AlertRelabelConfigs(namespace string) v1.AlertRelabelConfigInterface {
	return newFakeAlertRelabelConfigs(c, namespace)
}

func (c *FakeMonitoringV1) AlertingRules(namespace string) v1.AlertingRuleInterface {
	return newFakeAlertingRules(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMonitoringV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
